### ISSUE TITLE
Nineslice support

### ISSUE THREAD

**Issue by KINGTUT10101** [immortalx74/lovr-ui2d#3]
This library looks really amazing and I love the work on it so far! However, I think one thing that could set it apart from other libraries would be support for nineslices/ninepatches.

**Comment by immortalx74** [comment]
Thanks for the kind words! Another user suggested the same but I wouldn't know where to start. The actual part of defining and drawing a 9-patch is easy, but this library, as you see, isn't much code. It just draws a bunch of boxes for everything so it's more of a "toolbox" UI rather than a game-oriented UI which usually has nice and sleek design. I'm not against it, but the way the lib currently works is with simple rules like a universal margin size. You'd have to take care that the outside slices aren't bigger than this size, for example.
I'll give it a try when I find some time. I think the best way is to have the user choose if it'll use 9-patch vs simple drawing mode at the initialization function of the lib.

**Comment by immortalx74** [comment]
Forgot about this, sorry. Judging from feedback I got from users who like its simplicity, and mostly use it for debug or simple app UI, I'll leave it as is for now.
